-- Generated by tiraxis-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- Tiraxis and the Ethereal Bazaar, rebuilt from the client's own data: his
-- creature record and gossip from the client cache, his item pool from
-- VanityCollection, the fixed part of his inventory from a capture of the live
-- server's npc_vendor, and every price from ItemExtendedCost so the ordinary
-- vendor frame can charge Bazaar Tokens without a client patch.

-- Values taken from the client's own creature cache, entry 900007:
-- model 20986, rank 1 (elite), movementId 999, HealthModifier 2.48016.
-- npcflag is ours: 1 gossip + 128 vendor, because the gossip opens the lists.
DELETE FROM `creature_template` WHERE `entry` = 900007;
INSERT INTO `creature_template`
 (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`exp`,`faction`,`npcflag`,
  `speed_walk`,`speed_run`,`rank`,`unit_class`,`unit_flags`,`type`,`type_flags`,
  `AIName`,`MovementType`,`HealthModifier`,`ManaModifier`,`ArmorModifier`,
  `movementId`,`RegenHealth`,`flags_extra`,`ScriptName`)
VALUES
 (900007,'Tiraxis','The Ethereal Bazaar',80,80,2,35,129,
  1,1.14286,1,1,2,7,134217728,
  '',0,2.48016,1,1,
  999,1,2,'npc_tiraxis');

DELETE FROM `creature_template_model` WHERE `CreatureID` = 900007;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`)
VALUES (900007,0,20986,1,1);

DELETE FROM `npc_text` WHERE `ID` = 900007;
INSERT INTO `npc_text` (`ID`,`text0_0`,`text0_1`,`Probability0`)
VALUES (900007,'*Tiraxis eyes you up and down before speaking*$b$b Who I am, is unimportant. What matters is if we can bargain...$b$b Please, browse at your leisure... But do not idle, I have extremely limited stock pull new items from the ether multiple times a day.$b$bBazaar Tokens can be gathered by killing creatures, completing quests and are offered in the auction house.','*Tiraxis eyes you up and down before speaking*$b$b Who I am, is unimportant. What matters is if we can bargain...$b$b Please, browse at your leisure... But do not idle, I have extremely limited stock pull new items from the ether multiple times a day.$b$bBazaar Tokens can be gathered by killing creatures, completing quests and are offered in the auction house.',1);
